# Generated by Django 5.2.4 on 2025-08-21 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_registro_transacciones_id_prestamo_ref_deuda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='nombre',
            field=models.CharField(help_text="Un nombre único para identificar esta deuda (ej. 'Préstamo Coche')", max_length=100),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='plazo_meses',
            field=models.PositiveIntegerField(default=1, help_text='Para tarjetas de crédito, puede ser 1.'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El monto que se debe actualmente. Se actualiza con cada pago.', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='deuda',
            unique_together={('propietario', 'nombre')},
        ),
    ]
