# Generated by Django 5.2.4 on 2025-07-20 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_transaccionpendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inversiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inversion', models.CharField(choices=[('ACCION', 'Acción'), ('CRIPTO', 'Criptomoneda'), ('FONDO', 'Fondo de Inversión'), ('BONOS', 'Bonos'), ('FIBRAS', 'Fibras'), ('BIENES_RAICES', 'Bienes Raíces')], default='ACCION', max_length=30)),
                ('emisora_ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_activo', models.CharField(max_length=100)),
                ('cantidad_titulos', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fecha_compra', models.DateField()),
                ('precio_compra_titulo', models.DecimalField(decimal_places=10, max_digits=19)),
                ('tipo_cambio_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('costo_total_adquisicion', models.DecimalField(decimal_places=10, max_digits=20)),
                ('precio_actual_titulo', models.DecimalField(decimal_places=10, max_digits=19)),
                ('valor_actual_mercado', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ganancia_perdida_no_realizada', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ganancia_perdida', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada'), ('pendiente', 'Pendiente de Pago')], default='pendiente', max_length=15)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_suscripcion_mercadopago', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
