# Generated by Django 5.2.4 on 2025-08-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_amortizacionpendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_transacciones',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUALIDAD', 'Pago de Mensualidad'), ('CAPITAL', 'Pago a Capital')], default='MENSUALIDAD', max_length=15),
        ),
    ]
