# Generated by Django 5.2.4 on 2025-09-04 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_gananciamensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Un nombre único para identificar esta deuda (ej. 'Préstamo Coche')", max_length=100)),
                ('tipo_deuda', models.CharField(choices=[('PRESTAMO', 'Préstamo a Plazo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], default='PRESTAMO', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Para préstamos: el monto original. Para tarjetas de crédito: el límite de crédito total.', max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa de interés anual (%)', max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField(default=1, help_text='Para tarjetas de crédito, puede ser 1.')),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, help_text='El monto que se debe actualmente. Se actualiza con cada pago.', max_digits=12)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('propietario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AmortizacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_json', models.JSONField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones_pendientes', to='finanzas.deuda')),
            ],
        ),
        migrations.AddField(
            model_name='registro_transacciones',
            name='deuda_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.deuda'),
        ),
        migrations.CreateModel(
            name='PagoAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, help_text='IVA sobre los intereses', max_digits=10)),
                ('saldo_insoluto', models.DecimalField(decimal_places=2, help_text='Saldo pendiente después de este pago', max_digits=12)),
                ('pago_total', models.DecimalField(decimal_places=2, help_text='Suma de capital + interés + IVA', max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizacion', to='finanzas.deuda')),
                ('transaccion_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.registro_transacciones')),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='PendingInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_json', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
