# Generated by Django 5.2.4 on 2025-09-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_remove_registro_transacciones_id_prestamo_ref_deuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_transacciones',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUALIDAD', 'Pago de Mensualidad'), ('CAPITAL', 'Pago a Capital')], default='MENSUALIDAD', max_length=15),
        ),
    ]
