# Generated by Django 5.2.4 on 2025-11-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_registro_transacciones_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(help_text='Nombre único de la tienda o comercio', max_length=150, unique=True)),
                ('campos_requerdios', models.JSONField(default=list, help_text='Lista de campos requeridos para facturación electrónica')),
            ],
        ),
    ]
