# Generated by Django 5.2.4 on 2025-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_tiendafacturacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendafacturacion',
            name='campos_requerdios',
        ),
        migrations.AddField(
            model_name='tiendafacturacion',
            name='campos_requeridos',
            field=models.JSONField(default=list, help_text='Lista de llaves que necesitamos extraer para esta tienda'),
        ),
        migrations.AlterField(
            model_name='tiendafacturacion',
            name='tienda',
            field=models.CharField(help_text='Nombre normalizado de la tienda', max_length=150, unique=True),
        ),
    ]
