# Generated by Django 5.2.4 on 2025-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_remove_tiendafacturacion_campos_requerdios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_transacciones',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
