# Generated by Django 5.2.4 on 2025-12-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_registro_transacciones_datos_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(help_text='Nombre del establecimiento', max_length=150)),
                ('fecha_emision', models.DateField(help_text='Fecha del ticket/comprobante')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total', max_digits=12)),
                ('datos_facturacion', models.JSONField(default=dict, help_text='Datos extraídos para generar la factura')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Facturar'), ('facturado', 'Facturado')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
