# Generated by Django 5.2.4 on 2025-12-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_drive_id',
            field=models.CharField(blank=True, help_text='ID del archivo en Google Drive para ver la imagen original', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='configuracion_tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_generadas', to='finanzas.tiendafacturacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tiendafacturacion',
            name='url_portal',
            field=models.URLField(blank=True, help_text='Link directo al portal de facturación de esta tienda', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='datos_facturacion',
            field=models.JSONField(default=dict, help_text='Datos técnicos extraídos para el portal de facturación'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Facturar'), ('facturado', 'Facturado'), ('imposible', 'Datos insuficientes/Error')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha detectada en el ticket', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tienda',
            field=models.CharField(help_text='Nombre extraído del establecimiento', max_length=150),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del consumo', max_digits=12),
        ),
        migrations.AlterField(
            model_name='tiendafacturacion',
            name='campos_requeridos',
            field=models.JSONField(default=list, help_text="Lista de llaves que necesitamos extraer (ej. ['Folio', 'RFC', 'Código'])"),
        ),
        migrations.AlterField(
            model_name='tiendafacturacion',
            name='tienda',
            field=models.CharField(help_text='Nombre normalizado de la tienda (ej. WALMART, OXXO)', max_length=150, unique=True),
        ),
    ]
