# Generated by Django 5.2.4 on 2025-12-31 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_factura_archivo_drive_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_transacciones',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUALIDAD', 'Pago de Mensualidad'), ('CAPITAL', 'Pago a Capital'), ('TARJETA_CREDITO', 'Compra con Tarjeta de Crédito')], default='MENSUALIDAD', max_length=15),
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capital_invertido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ganancia_no_realizada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
