# Generated by Django 5.2.4 on 2025-12-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_registro_transacciones_tipo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendafacturacion',
            name='configuracion_finalizada',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya confirmó que esta configuración es correcta/completa.'),
        ),
    ]
