# Generated by Django 5.2.4 on 2026-04-07 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_tiendafacturacion_configuracion_finalizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha detectada en el ticket', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tienda',
            field=models.CharField(db_index=True, help_text='Nombre extraído del establecimiento', max_length=150),
        ),
        migrations.AlterField(
            model_name='registro_transacciones',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_transacciones',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='registro_transacciones',
            name='monto',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='registro_transacciones',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia')], db_index=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Tarjeta Banamex, Efectivo Quincena, NuBank', max_length=50)),
                ('terminacion', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta (opcional)', max_length=4, null=True)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('INVERSION', 'Cuenta de Inversión')], default='DEBITO', max_length=15)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('propietario', 'nombre')},
            },
        ),
    ]
