# Generated by Django 5.2.4 on 2026-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_alter_factura_fecha_emision_alter_factura_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='requiere_configuracion_adicional',
            field=models.BooleanField(default=False, help_text='Indica si la deuda se generó automáticamente y necesita que se configuren sus detalles (monto, tasa, etc.)'),
        ),
    ]
