# Generated by Django 5.2.4 on 2026-04-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_deuda_requiere_configuracion_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='dia_corte',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes en que corta la tarjeta (1-31). Ej: 6', null=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='dia_pago',
            field=models.PositiveIntegerField(blank=True, help_text='Día límite de pago del mes (1-31). Ej: 30', null=True),
        ),
    ]
