# Generated by Django 5.2.4 on 2026-04-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_registro_transacciones_tipo_pago'),
        ('finanzas', '0015_deuda_dia_corte_deuda_dia_pago'),
    ]

    operations = [
    ]
