# Generated by Django 5.2.4 on 2026-04-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_cuenta_es_principal'),
    ]

    operations = [

        migrations.AlterField(
            model_name='registro_transacciones',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MENSUALIDAD', 'Pago de Mensualidad'), ('PAGO_CAPITAL', 'Pago a Capital')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registro_transacciones',
            name='tipo_pago',
            field=models.CharField(choices=[('MENSUALIDAD', 'Pago de Mensualidad'), ('CAPITAL', 'Pago a Capital'), ('TARJETA_CREDITO', 'Compra con Tarjeta de Crédito')], default='MENSUALIDAD', max_length=15),
        ),
    ]
