# Generated by Django 5.2.4 on 2026-05-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0018_deuda_dia_corte_deuda_dia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='dia_corte',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes en que corta la tarjeta (1-31). Ej: 6', null=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='dia_pago',
            field=models.PositiveIntegerField(blank=True, help_text='Día límite de pago del mes (1-31). Ej: 30', null=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='requiere_configuracion_adicional',
            field=models.BooleanField(default=False, help_text='Indica si la deuda se generó automáticamente y necesita que se configuren sus detalles (monto, tasa, etc.)'),
        ),
    ]
