# Generated by Django 5.2.4 on 2026-05-31 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_deuda_dia_corte_deuda_dia_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ej. Vivienda, Alimentación, Transporte', max_length=100)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('es_recurrente', models.BooleanField(default=True, help_text='Si es verdadero, aplica para todos los meses')),
                ('mes', models.IntegerField(blank=True, help_text='Mes específico (1-12) si no es recurrente', null=True)),
                ('anio', models.IntegerField(blank=True, help_text='Año específico si no es recurrente', null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'unique_together': {('propietario', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
