# Generated by Django 5.2.4 on 2026-05-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_historialreciboservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_proximo_recibo',
            field=models.DateField(blank=True, help_text='Fecha estimada del próximo recibo (generada por IA)', null=True),
        ),
    ]
