# Generated by Django 5.2.4 on 2026-06-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_presupuesto_fecha_proximo_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='monto_real',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto real gastado o facturado', max_digits=12),
        ),
    ]
